[package]
name = "rhai-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version="1.47.1", features=["full"]}
poem = "3"
poem-openapi = { version = "5", features = ["swagger-ui"]}
rhai = "1.22.2"
reqwest = { version = "0.12.23", features = ["json", "blocking"] }
rayon = "1.11.0"
